# Generated by Django 6.0.3 on 2026-03-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='longitude',
        ),
    ]
