# Generated by Django 6.0.3 on 2026-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_remove_checkin_latitude_remove_checkin_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
