# Generated by Django 6.0.3 on 2026-03-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_checkin_latitude_checkin_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
