# Generated by Django 6.0.3 on 2026-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('1', 'กองร้อย 1'), ('2', 'กองร้อย 2'), ('3', 'กองร้อย 3'), ('4', 'กองร้อย 4'), ('5', 'กองร้อยสนับสนุน')], default='1', max_length=10),
        ),
    ]
