# Generated by Django 6.0.3 on 2026-05-19 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0010_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person_status',
            field=models.CharField(choices=[('normal', 'ปกติ'), ('leave', 'ลาพัก'), ('mission', 'ไปราชการ'), ('home', 'กลับบ้าน')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
