# Generated by Django 6.0.3 on 2026-05-19 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0011_userprofile_created_at_userprofile_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfaceprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
