# Generated by Django 6.0.3 on 2026-05-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0013_alter_checkinrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='latitude',
            field=models.FloatField(default=13.81981, verbose_name='ละติจูดที่ตั้งหน่วย'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='longitude',
            field=models.FloatField(default=100.529614, verbose_name='ลองจิจูดที่ตั้งหน่วย'),
        ),
    ]
