# Generated by Django 6.0.3 on 2026-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0014_systemsetting_latitude_systemsetting_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinrecord',
            old_name='distance',
            new_name='distance_meters',
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='confidence_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='verification_method',
            field=models.CharField(blank=True, default='face', max_length=50, null=True),
        ),
    ]
