# Generated by Django 6.0.3 on 2026-05-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0015_rename_distance_checkinrecord_distance_meters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='return_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='individual_return_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันและเวลากลับเข้ากรมรายบุคคล'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='return_status',
            field=models.CharField(choices=[('PENDING', 'ยังไม่รายงานตัว ⏳'), ('ON_TIME', 'กลับทันเวลา ✅'), ('LATE', 'กลับไม่ทันเวลา ❌')], default='PENDING', max_length=20, verbose_name='สถานะการกลับรายงานตัว'),
        ),
    ]
