# Generated by Django 6.0.3 on 2026-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0016_remove_userprofile_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มต้นออกกรม'),
        ),
    ]
