# Generated by Django 6.0.3 on 2026-05-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0017_userprofile_start_date'),
    ]

    operations = [
    ]
