# Generated by Django 6.0.3 on 2026-05-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0018_auto_20260523_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('ร้อย.บก.', 'กองร้อยกองบังคับการ (ร้อย.บก.)'), ('ร้อย.1', 'กองร้อยที่ 1'), ('ร้อย.2', 'กองร้อยที่ 2'), ('ร้อย.3', 'กองร้อยที่ 3'), ('ร้อย.4', 'กองร้อยที่ 4'), ('ร้อย.สสห.', 'กองร้อยสนับสนุน (ร้อย.สสห.)')], default='ร้อย.บก.', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_status',
            field=models.CharField(choices=[('normal', 'ปกติ (อยู่ในค่าย)'), ('leave', 'ลาพัก'), ('mission', 'ไปราชการ'), ('official', 'ปฏิบัติภารกิจนอกค่าย'), ('home', 'กลับบ้าน / ออกกรม')], default='normal', max_length=20),
        ),
    ]
