# Generated by Django 6.0.3 on 2026-05-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0019_alter_userprofile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('กองร้อยกองบังคับการ', 'กองร้อยกองบังคับการ'), ('กองร้อยที่ 1', 'กองร้อยที่ 1'), ('กองร้อยที่ 2', 'กองร้อยที่ 2'), ('กองร้อยที่ 3', 'กองร้อยที่ 3'), ('กองร้อยที่ 4', 'กองร้อยที่ 4'), ('กองร้อยสนับสนุน', 'กองร้อยสนับสนุน')], default='กองร้อยกองบังคับการ', max_length=50),
        ),
    ]
